davpro: davpro.c
	c++ davpro.c -o davpro

ping:
	ping 192.168.1.7

runv:
	./davpro -v 192.168.1.7 9100

runu:
	./davpro -u 192.168.1.7 9100 SmallTestRing-abs.3w

runj:
	./davpro -j 192.168.1.7 9100

rund:
	./davpro -d 192.168.1.7 9100

